[package]
name = "riverbed"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "crates/*"
]

[dependencies]
bevy = { version = "0.16" }
bevy_atmosphere = "*"
binary-greedy-meshing = "*"
confy = "*"
leafwing-input-manager = { git = "https://github.com/Leafwing-Studios/leafwing-input-manager.git", branch = "main" }
rand = "*"
rand_chacha = "*"
indexmap = "*"
itertools = "*"
vpsearch = "*"
parking_lot = "*"
crossbeam = "*"
csv = "*"
colorsys = "*"
anyhow = "*"
serde = "*"
strum = "*"
strum_macros = "*"
dashmap = "*"
futures-lite = "*"
array-macro = "*"
packed-uints = "*"
block-mesh = "*"
lazy_static = "*"
noise-algebra = "*"
regex = "*"
json5 = "*"
riverbed_closest = { path = "crates/riverbed_closest", version = "*" }

[build-dependencies]
riverbed_block_def = { path = "crates/riverbed_block_def", version = "*" }

[profile.dev]
opt-level = 1
