[package]
name = "riverbed"
version = "0.1.0"
edition = "2024"

[features]
verbose = []
log_inspector = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[workspace]
members = [
    "crates/*"
]

[dependencies]
anyhow = "*"
bevy = { version = "0.16" }
bevy_atmosphere = "*"
binary-greedy-meshing = "*"
cfg-if = "*"
chrono = { version = "*", features = ["serde", "rkyv"] }
confy = "*"
crossbeam = "*"
csv = "*"
dashmap = "*"
itertools = "*"
json5 = "*"
lazy_static = "*"
leafwing-input-manager = { git = "https://github.com/Leafwing-Studios/leafwing-input-manager.git", branch = "main" }
noise-algebra = "*"
packed-uints = "*"
parking_lot = "*"
rand = "*"
rand_chacha = "*"
regex = "*"
riverbed_closest = { path = "crates/riverbed_closest", version = "*" }
ron = "*"
serde = "*"
strum = "*"
strum_macros = "*"

[build-dependencies]
riverbed_block_def = { path = "crates/riverbed_block_def", version = "*" }

[profile.dev]
opt-level = 1
