mod utils;
mod chunk;
mod blocs;
mod pos;
mod bloc;
mod realm;
pub mod growables;
pub use bloc::*;
pub use realm::*;
pub use blocs::*;
pub use chunk::*;
pub use pos::*;
pub use utils::*;
pub const CHUNK_S1: usize = 32;
pub const MAX_GEN_HEIGHT: usize = 200;
pub const MAX_HEIGHT: usize = 256;
pub const Y_CHUNKS: usize = MAX_HEIGHT/CHUNK_S1;